cmake_minimum_required(VERSION 3.11)
project(sandbox)

include(cmake/CPM.cmake)

CPMAddPackage(
    NAME raylib
    GITHUB_REPOSITORY "raysan5/raylib"
    GIT_TAG "6.0"
    EXCLUDE_FROM_ALL TRUE
    OPTIONS
        "GLFW_BUILD_WAYLAND ON"
)

CPMAddPackage("gh:raysan5/raygui#4.0")

CPMAddPackage(
    NAME mbedtls
    GITHUB_REPOSITORY "ARMmbed/mbedtls"
    GIT_TAG "v3.1.0"
    EXCLUDE_FROM_ALL TRUE
    OPTIONS
        "ENABLE_PROGRAMS OFF"
        "ENABLE_TESTING OFF"
        "MBEDTLS_FATAL_WARNINGS OFF"
)

set(MBEDTLS_INCLUDE_DIRS ${mbedtls_SOURCE_DIR}/include)
set(MBEDTLS_LIBRARIES mbedtls)
set(MBEDX509_LIBRARY mbedtls)
set(MBEDCRYPTO_LIBRARY mbedtls)

CPMAddPackage(
    NAME curl
    GITHUB_REPOSITORY "curl/curl"
    GIT_TAG "curl-7_82_0"
    EXCLUDE_FROM_ALL TRUE
    OPTIONS
        "CMAKE_USE_LIBSSH2 OFF"
        "CURL_USE_MBEDTLS ON"
        "BUILD_CURL_EXE OFF"
        "BUILD_SHARED_LIBS OFF"
        "BUILD_TESTING OFF"
        "USE_MANUAL OFF"
        "CURL_USE_SCHANNEL OFF"
        "CURL_WINDOWS_SSPI OFF"
)

file(GLOB SOURCES src/screen/*.c src/*.c)

add_executable(${PROJECT_NAME} ${SOURCES})

target_include_directories(${PROJECT_NAME} PRIVATE 
    ${CMAKE_SOURCE_DIR}/src
    ${raylib_SOURCE_DIR}/src/external
    ${raygui_SOURCE_DIR}/src
    ${curl_SOURCE_DIR}/include
)

target_link_libraries(${PROJECT_NAME} raylib libcurl)
target_compile_definitions(${PROJECT_NAME} PUBLIC _CRT_SECURE_NO_WARNINGS)


add_custom_command(
    TARGET ${PROJECT_NAME} POST_BUILD
    COMMAND ${CMAKE_COMMAND} -E copy_directory
            "${CMAKE_SOURCE_DIR}/resources"
            "$<TARGET_FILE_DIR:${PROJECT_NAME}>/resources"
)

find_package(Git REQUIRED)

execute_process(
    COMMAND ${GIT_EXECUTABLE} log -1 --format=%h
    WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
    OUTPUT_VARIABLE GIT_SHORTSHA
    OUTPUT_STRIP_TRAILING_WHITESPACE
)
string(TOLOWER ${CMAKE_SYSTEM_NAME} SYSTEM_NAME)
set(CPACK_PACKAGE_NAME "sandboxforfriends")
set(CPACK_PACKAGE_FILE_NAME ${CPACK_PACKAGE_NAME}-${SYSTEM_NAME})
set(CPACK_PACKAGE_VENDOR "sandboxforfriends")
set(CPACK_PACKAGE_VERSION "${PROJECT_VERSION}")
set(CPACK_PACKAGE_DIRECTORY "${CMAKE_BINARY_DIR}/package")
set(CMAKE_INSTALL_PREFIX "${CMAKE_BINARY_DIR}/install")
set(CPACK_GENERATOR "ZIP")

set(GIT_REPO "https://github.com/SFF-Developers-Team/SFF-Sandbox")

install(TARGETS sandbox RUNTIME DESTINATION .)

install(DIRECTORY "${CMAKE_SOURCE_DIR}/resources" DESTINATION .)

string(TIMESTAMP CURRENT_DATE "%Y-%m-%d")
string(TIMESTAMP CURRENT_TIME "%H:%M:%S")

set(VERSION_STR "${PROJECT_VERSION}")

if(CMAKE_BUILD_TYPE STREQUAL "Debug") 
    set(VERSION_STR "${VERSION_STR} - Development Build")
endif()

file(WRITE "${CMAKE_BINARY_DIR}/version.txt"
"Sandbox for Friends ${VERSION_STR}

Autogenerated file by cmake-${CMAKE_VERSION}.
Report issues ${GIT_REPO}/issues

Build date: ${CURRENT_DATE} ${CURRENT_TIME}
Build configuration: ${CMAKE_BUILD_TYPE}
Git commit: ${GIT_SHORTSHA}
Platform: ${CMAKE_SYSTEM_NAME}")

install(FILES "${CMAKE_BINARY_DIR}/version.txt" DESTINATION .) 

include(CPack)