[root]
size = [650, 450]
child_scaling = 4

[base-rect]
object_type = "Rectangle"
size = [650, 450]
col = [34, 117, 109]
z_order = 0

[line-rect]
object_type = "Rectangle"
size = [650, 450]
col = [49, 132, 124]
solid = false
thickness = 6
z_order = 1

[line-rect-shadow]
object_type = "Rectangle"
size = [650, 450]
col = [0, 0, 0]
solid = false
thickness = 6
z_order = -1
pos = [6, 6]

[credits-label]
object_type = "Text"
label = "Credits"
aligned_x = true
pos = [0, 10]
col = [255, 255, 255]
font_size = 40
spacing = 2
z_order = 2
shadow_enabled = true

[kolyah35-img]
object_type = "Sprite"
image_path = "assets/kolyah35.png"
col = [255, 255, 255]
scale = 0.25
z_order = 1
pos = [20, 75]

[kolyah35-name]
object_type = "Text"
label = "Kolyah35"
col = [255, 255, 255]
font_size = 20
z_order = 1
pos = [35, 200]
shadow_enabled = true

[sergeymc9730-img]
object_type = "Sprite"
image_path = "assets/sergeymc9730.png"
col = [255, 255, 255]
scale = 0.32
z_order = 1
pos = [220, 65]

[sergeymc9730-name]
object_type = "Text"
label = "SergeyMC9730"
col = [255, 255, 255]
font_size = 20
z_order = 1
pos = [220, 200]
shadow_enabled = true

[invisedivine-img]
object_type = "Sprite"
image_path = "assets/invisedivine.png"
col = [255, 255, 255]
scale = 0.4
z_order = 1
pos = [460, 75]

[invisedivine-name]
object_type = "Text"
label = "InviseDivine"
col = [255, 255, 255]
font_size = 20
z_order = 1
pos = [470, 200]
shadow_enabled = true

[next-btn]
object_type = "Button"
label = "Next"
font_size = 20
z_order = 1
pos = [0, 250]
aligned_x = true
size = [200, 40]
col = [70, 74, 15]